# Generated by Django 5.1.4 on 2025-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
