# Generated by Django 5.1.4 on 2025-09-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMartApp', '0002_remove_product_categories_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_tracking', to='DjangoMartApp.purchase'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('purchase_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='DjangoMartApp.purchaseitem')),
            ],
        ),
    ]
