# Generated by Django 5.1.4 on 2025-09-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMartApp', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item', to='DjangoMartApp.product'),
        ),
    ]
