# Generated by Django 5.2.6 on 2025-09-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMartApp', '0007_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date']},
        ),
    ]
