# Generated by Django 5.1.4 on 2025-09-25 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMartApp', '0008_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
