# constants related to training / infering a model that is trained on sales data
TRAINING_YEARS = [2024, 2025]

# sequential model constants
SEQUENTIAL_MODEL_TYPE = 'sequential_model'
NUMERIC_SEQUENTIAL_MODEL_SALES_COLUMNS = ['TOTAL_TRANSACTIONS_COUNT', 'LAST_DAY_SALES', 'LAST_7_DAYS_SALES',
                    'LAST_14_DAYS_SALES', 'LAST_30_DAYS_SALES']
X_COLUMNS_SEQUENTIAL_MODEL = ['TOTAL_TRANSACTIONS_COUNT', 'DAY_SIN', 'DAY_COS',
                'IS_WEEKEND', 'LAST_DAY_SALES', 'LAST_7_DAYS_SALES',
                'MONTH_SIN', 'MONTH_COS', 'LAST_14_DAYS_SALES',
                'LAST_30_DAYS_SALES']
Y_COLUMNS_SEQUENTIAL_MODEL = ['TOTAL_TOKENS_SPENT']

# LSTM model constants
LSTM_MODEL_TYPE = 'LSTM_model'
NUMERIC_LSTM_MODEL_SALES_COLUMNS = ['TOTAL_TRANSACTIONS_COUNT']
X_COLUMNS_LSTM_MODEL = ['TOTAL_TRANSACTIONS_COUNT', 'DAY_SIN', 'DAY_COS',
                'IS_WEEKEND', 'LAST_DAY_SALES', 
                'MONTH_SIN', 'MONTH_COS',]
Y_COLUMNS_LSTM_MODEL = ['TOTAL_TOKENS_SPENT']

# general mapper
MODEL_COLUMN_MAPPER = {
    SEQUENTIAL_MODEL_TYPE: {
        'X_COLUMNS': X_COLUMNS_SEQUENTIAL_MODEL,
        'Y_COLUMNS': Y_COLUMNS_SEQUENTIAL_MODEL,
        'NUMERIC_COLUMNS': NUMERIC_SEQUENTIAL_MODEL_SALES_COLUMNS
    },
    LSTM_MODEL_TYPE: {
        'X_COLUMNS': X_COLUMNS_LSTM_MODEL,
        'Y_COLUMNS': Y_COLUMNS_LSTM_MODEL,
        'NUMERIC_COLUMNS': NUMERIC_LSTM_MODEL_SALES_COLUMNS
    }
}