SELECT 
    DATE_TRUNC('month', GENERATED_DATETIME::DATE) AS GENERATED_MONTH,
    SUM(total_price) AS TOTAL_TOKENS_SPENT,
    LAG(TOTAL_TOKENS_SPENT) OVER (ORDER BY GENERATED_MONTH) AS PREVIOUS_MONTH_TOKENS_SPENT,
    ROUND
    (
        (TOTAL_TOKENS_SPENT - PREVIOUS_MONTH_TOKENS_SPENT) 
        /
        IFNULL(PREVIOUS_MONTH_TOKENS_SPENT, 0) * 100
        , 2
    ) AS TOKENS_SPENT_PERCENTAGE_CHANGE,
    COUNT(*) AS TOTAL_TRANSACTIONS_COUNT
FROM {{ ref('historic_djangomart_purchases') }}
WHERE DWH_IS_LATEST = 1
GROUP BY GENERATED_MONTH