SELECT 
    DATE_TRUNC('day', GENERATED_DATETIME::DATE) AS GENERATED_DAY,
    SUM(total_price) AS TOTAL_TOKENS_SPENT,
    EXTRACT(ISODOW FROM GENERATED_DAY) AS DAY_OF_THE_WEEK,
    EXTRACT(MONTH FROM GENERATED_DAY) AS RECORD_MONTH,
    EXTRACT(YEAR FROM GENERATED_DAY) AS RECORD_YEAR,
    IF(DAY_OF_THE_WEEK IN (6,7), 1, 0) AS IS_WEEKEND,
    LAG(TOTAL_TOKENS_SPENT) OVER (ORDER BY GENERATED_DAY) AS LAST_DAY_SALES,
    SUM(TOTAL_TOKENS_SPENT) OVER 
    (
        ORDER BY GENERATED_DAY
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS LAST_7_DAYS_SALES,
    SUM(TOTAL_TOKENS_SPENT) OVER 
    (
        ORDER BY GENERATED_DAY
        ROWS BETWEEN 13 PRECEDING AND CURRENT ROW
    ) AS LAST_14_DAYS_SALES,
    SUM(TOTAL_TOKENS_SPENT) OVER 
    (
        ORDER BY GENERATED_DAY
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS LAST_30_DAYS_SALES,
    COUNT(*) AS TOTAL_TRANSACTIONS_COUNT
FROM {{ ref('historic_djangomart_purchases') }}
WHERE DWH_IS_LATEST = 1
GROUP BY GENERATED_DAY
ORDER BY GENERATED_DAY