
version: 2

models:
  - name: raw_djangomart_purchases
    description: "Purchase data coming from the djangomart source system"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique:
              arguments: {}
              severity: warn
          - not_null:
              arguments: {}
              severity: warn

