version: 2

sources:
  - name: djangomart_products
    tables:
      - name: dummy
        meta:
          dagster:
            asset_key: ['get_products']
  - name: djangomart_purchases
    tables:
      - name: dummy
        meta:
          dagster:
            asset_key: ['get_purchases']
  - name: djangomart_purchase_items
    tables:
      - name: dummy
        meta:
          dagster:
            asset_key: ['get_purchase_items']
  - name: djangomart_users
    tables:
      - name: dummy
        meta:
          dagster:
            asset_key: ['get_users']
  - name: djangomart_categories
    tables:
      - name: dummy
        meta:
          dagster:
            asset_key: ['get_categories']