
version: 2

models:
  - name: semantic_djangomart_purchases
    description: |
     Purchase data coming from the djangomart source system with
     its columns clearly and consistenly named and its types casted
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - not_null:
              arguments: {}
              severity: error
      - name: TOTAL_PRICE
        description: "Total price paid by user at checkout"
        tests:
          - not_null:
              arguments: {}
              severity: warn
      - name: IS_INVALID
        description: "Flags invalid records"
      - name: CREATED_DATE
        description: "Datetime in which the record was inserted"
        tests:
          - not_null:
              arguments: {}
              severity: warn
      - name: UPDATED_DATE
        description: "Datetime in which a record was last modified"
      - name: USER
        description: "The id of the user who made the purchase, coming from the source system"
        tests:
          - not_null:
              arguments: {}
              severity: warn
      

